

APP_OPTIM        := debug
#APP_OPTIM        := release


ifeq ($(CSS_BUILD_TARGET),armv4t)
APP_ABI := armv4t 
else
ifeq ($(CSS_BUILD_TARGET),armeabi)
APP_ABI := armeabi 
else
ifeq ($(CSS_BUILD_TARGET),armeabi-v7a)
APP_ABI := armeabi-v7a
else
APP_ABI := armeabi armeabi-v7a
endif
endif
endif

MY_USE_CSIPSIMPLE := 1

MY_USE_G729 := 1
MY_USE_ILBC := 0
MY_USE_G722 := 1
MY_USE_G7221 := 1
MY_USE_SPEEX := 1
MY_USE_GSM := 1
MY_USE_SILK := 1
MY_USE_CODEC2 := 1
MY_USE_TLS := 1
MY_USE_WEBRTC := 1
MY_USE_AMR := 1

MY_ANDROID_DEV := 1



# Do not change behind this line the are flags for pj build
# Only build pjsipjni and ignore openssl
APP_MODULES := libpjsipjni pj_opensl_dev
ifeq ($(MY_USE_SILK),1)
APP_MODULES += libpj_silk_codec 
endif
ifeq ($(MY_USE_G7221),1)
APP_MODULES += libpj_g7221_codec
endif
ifeq ($(MY_USE_CODEC2),1)
APP_MODULES += libpj_codec2_codec
endif

APP_PLATFORM := android-9
APP_STL := stlport_static

BASE_PJSIP_FLAGS := -DPJ_ANDROID=1 -DUSE_CSIPSIMPLE=$(MY_USE_CSIPSIMPLE)
# about codecs
BASE_PJSIP_FLAGS += -DPJMEDIA_HAS_G729_CODEC=$(MY_USE_G729) \
	-DPJMEDIA_HAS_ILBC_CODEC=$(MY_USE_ILBC) -DPJMEDIA_HAS_G722_CODEC=$(MY_USE_G722) \
	-DPJMEDIA_HAS_SPEEX_CODEC=$(MY_USE_SPEEX) -DPJMEDIA_HAS_GSM_CODEC=$(MY_USE_GSM) \
	-DPJMEDIA_HAS_SILK_CODEC=$(MY_USE_SILK) -DPJMEDIA_HAS_CODEC2_CODEC=$(MY_USE_CODEC2) \
	-DPJMEDIA_HAS_G7221_CODEC=$(MY_USE_G7221) -DPJMEDIA_HAS_WEBRTC_CODEC=$(MY_USE_WEBRTC) \
	-DPJMEDIA_HAS_AMR_STAGEFRIGHT_CODEC=$(MY_USE_AMR)

# media
BASE_PJSIP_FLAGS += -DPJMEDIA_HAS_WEBRTC_AEC=$(MY_USE_WEBRTC) \
	-DPJMEDIA_HAS_VIDEO=1 -DPJ_ANDROID_DEVICE=$(MY_ANDROID_DEV)
# TLS ZRTP
BASE_PJSIP_FLAGS += -DPJ_HAS_SSL_SOCK=$(MY_USE_TLS) -DPJMEDIA_HAS_ZRTP=$(MY_USE_TLS)
	 
