/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pj_ice_sess_options {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pj_ice_sess_options(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pj_ice_sess_options obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsuaJNI.delete_pj_ice_sess_options(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAggressive(int value) {
    pjsuaJNI.pj_ice_sess_options_aggressive_set(swigCPtr, this, value);
  }

  public int getAggressive() {
    return pjsuaJNI.pj_ice_sess_options_aggressive_get(swigCPtr, this);
  }

  public void setNominated_check_delay(long value) {
    pjsuaJNI.pj_ice_sess_options_nominated_check_delay_set(swigCPtr, this, value);
  }

  public long getNominated_check_delay() {
    return pjsuaJNI.pj_ice_sess_options_nominated_check_delay_get(swigCPtr, this);
  }

  public void setControlled_agent_want_nom_timeout(int value) {
    pjsuaJNI.pj_ice_sess_options_controlled_agent_want_nom_timeout_set(swigCPtr, this, value);
  }

  public int getControlled_agent_want_nom_timeout() {
    return pjsuaJNI.pj_ice_sess_options_controlled_agent_want_nom_timeout_get(swigCPtr, this);
  }

  public pj_ice_sess_options() {
    this(pjsuaJNI.new_pj_ice_sess_options(), true);
  }

}
