/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public enum pj_turn_tp_type {
  PJ_TURN_TP_UDP(pjsuaJNI.PJ_TURN_TP_UDP_get()),
  PJ_TURN_TP_TCP(pjsuaJNI.PJ_TURN_TP_TCP_get()),
  PJ_TURN_TP_TLS(pjsuaJNI.PJ_TURN_TP_TLS_get());

  public final int swigValue() {
    return swigValue;
  }

  public static pj_turn_tp_type swigToEnum(int swigValue) {
    pj_turn_tp_type[] swigValues = pj_turn_tp_type.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (pj_turn_tp_type swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + pj_turn_tp_type.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private pj_turn_tp_type() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private pj_turn_tp_type(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private pj_turn_tp_type(pj_turn_tp_type swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

