/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjsua_vid_win_info {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjsua_vid_win_info(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjsua_vid_win_info obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsuaJNI.delete_pjsua_vid_win_info(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIs_native(int value) {
    pjsuaJNI.pjsua_vid_win_info_is_native_set(swigCPtr, this, value);
  }

  public int getIs_native() {
    return pjsuaJNI.pjsua_vid_win_info_is_native_get(swigCPtr, this);
  }

  public void setHwnd(SWIGTYPE_p_pjmedia_vid_dev_hwnd value) {
    pjsuaJNI.pjsua_vid_win_info_hwnd_set(swigCPtr, this, SWIGTYPE_p_pjmedia_vid_dev_hwnd.getCPtr(value));
  }

  public SWIGTYPE_p_pjmedia_vid_dev_hwnd getHwnd() {
    return new SWIGTYPE_p_pjmedia_vid_dev_hwnd(pjsuaJNI.pjsua_vid_win_info_hwnd_get(swigCPtr, this), true);
  }

  public void setRdr_dev(SWIGTYPE_p_pjmedia_vid_dev_index value) {
    pjsuaJNI.pjsua_vid_win_info_rdr_dev_set(swigCPtr, this, SWIGTYPE_p_pjmedia_vid_dev_index.getCPtr(value));
  }

  public SWIGTYPE_p_pjmedia_vid_dev_index getRdr_dev() {
    return new SWIGTYPE_p_pjmedia_vid_dev_index(pjsuaJNI.pjsua_vid_win_info_rdr_dev_get(swigCPtr, this), true);
  }

  public void setShow(int value) {
    pjsuaJNI.pjsua_vid_win_info_show_set(swigCPtr, this, value);
  }

  public int getShow() {
    return pjsuaJNI.pjsua_vid_win_info_show_get(swigCPtr, this);
  }

  public void setPos(SWIGTYPE_p_pjmedia_coord value) {
    pjsuaJNI.pjsua_vid_win_info_pos_set(swigCPtr, this, SWIGTYPE_p_pjmedia_coord.getCPtr(value));
  }

  public SWIGTYPE_p_pjmedia_coord getPos() {
    return new SWIGTYPE_p_pjmedia_coord(pjsuaJNI.pjsua_vid_win_info_pos_get(swigCPtr, this), true);
  }

  public void setSize(SWIGTYPE_p_pjmedia_rect_size value) {
    pjsuaJNI.pjsua_vid_win_info_size_set(swigCPtr, this, SWIGTYPE_p_pjmedia_rect_size.getCPtr(value));
  }

  public SWIGTYPE_p_pjmedia_rect_size getSize() {
    return new SWIGTYPE_p_pjmedia_rect_size(pjsuaJNI.pjsua_vid_win_info_size_get(swigCPtr, this), true);
  }

  public pjsua_vid_win_info() {
    this(pjsuaJNI.new_pjsua_vid_win_info(), true);
  }

}
