/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public enum pjsua_vid_req_keyframe_method {
  PJSUA_VID_REQ_KEYFRAME_SIP_INFO(pjsuaJNI.PJSUA_VID_REQ_KEYFRAME_SIP_INFO_get()),
  PJSUA_VID_REQ_KEYFRAME_RTCP_PLI(pjsuaJNI.PJSUA_VID_REQ_KEYFRAME_RTCP_PLI_get());

  public final int swigValue() {
    return swigValue;
  }

  public static pjsua_vid_req_keyframe_method swigToEnum(int swigValue) {
    pjsua_vid_req_keyframe_method[] swigValues = pjsua_vid_req_keyframe_method.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (pjsua_vid_req_keyframe_method swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + pjsua_vid_req_keyframe_method.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private pjsua_vid_req_keyframe_method() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private pjsua_vid_req_keyframe_method(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private pjsua_vid_req_keyframe_method(pjsua_vid_req_keyframe_method swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

