/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjsua_transport_info {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjsua_transport_info(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjsua_transport_info obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsuaJNI.delete_pjsua_transport_info(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(int value) {
    pjsuaJNI.pjsua_transport_info_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return pjsuaJNI.pjsua_transport_info_id_get(swigCPtr, this);
  }

  public void setType(pjsip_transport_type_e value) {
    pjsuaJNI.pjsua_transport_info_type_set(swigCPtr, this, value.swigValue());
  }

  public pjsip_transport_type_e getType() {
    return pjsip_transport_type_e.swigToEnum(pjsuaJNI.pjsua_transport_info_type_get(swigCPtr, this));
  }

  public void setType_name(pj_str_t value) {
    pjsuaJNI.pjsua_transport_info_type_name_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getType_name() {
    long cPtr = pjsuaJNI.pjsua_transport_info_type_name_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setInfo(pj_str_t value) {
    pjsuaJNI.pjsua_transport_info_info_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getInfo() {
    long cPtr = pjsuaJNI.pjsua_transport_info_info_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setFlag(long value) {
    pjsuaJNI.pjsua_transport_info_flag_set(swigCPtr, this, value);
  }

  public long getFlag() {
    return pjsuaJNI.pjsua_transport_info_flag_get(swigCPtr, this);
  }

  public void setAddr_len(long value) {
    pjsuaJNI.pjsua_transport_info_addr_len_set(swigCPtr, this, value);
  }

  public long getAddr_len() {
    return pjsuaJNI.pjsua_transport_info_addr_len_get(swigCPtr, this);
  }

  public void setLocal_addr(SWIGTYPE_p_pj_sockaddr value) {
    pjsuaJNI.pjsua_transport_info_local_addr_set(swigCPtr, this, SWIGTYPE_p_pj_sockaddr.getCPtr(value));
  }

  public SWIGTYPE_p_pj_sockaddr getLocal_addr() {
    return new SWIGTYPE_p_pj_sockaddr(pjsuaJNI.pjsua_transport_info_local_addr_get(swigCPtr, this), true);
  }

  public void setLocal_name(SWIGTYPE_p_pjsip_host_port value) {
    pjsuaJNI.pjsua_transport_info_local_name_set(swigCPtr, this, SWIGTYPE_p_pjsip_host_port.getCPtr(value));
  }

  public SWIGTYPE_p_pjsip_host_port getLocal_name() {
    return new SWIGTYPE_p_pjsip_host_port(pjsuaJNI.pjsua_transport_info_local_name_get(swigCPtr, this), true);
  }

  public void setUsage_count(long value) {
    pjsuaJNI.pjsua_transport_info_usage_count_set(swigCPtr, this, value);
  }

  public long getUsage_count() {
    return pjsuaJNI.pjsua_transport_info_usage_count_get(swigCPtr, this);
  }

  public pjsua_transport_info() {
    this(pjsuaJNI.new_pjsua_transport_info(), true);
  }

}
