/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class csipsimple_config {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public csipsimple_config(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(csipsimple_config obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsuaJNI.delete_csipsimple_config(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUse_compact_form_sdp(int value) {
    pjsuaJNI.csipsimple_config_use_compact_form_sdp_set(swigCPtr, this, value);
  }

  public int getUse_compact_form_sdp() {
    return pjsuaJNI.csipsimple_config_use_compact_form_sdp_get(swigCPtr, this);
  }

  public void setUse_compact_form_headers(int value) {
    pjsuaJNI.csipsimple_config_use_compact_form_headers_set(swigCPtr, this, value);
  }

  public int getUse_compact_form_headers() {
    return pjsuaJNI.csipsimple_config_use_compact_form_headers_get(swigCPtr, this);
  }

  public void setUse_no_update(int value) {
    pjsuaJNI.csipsimple_config_use_no_update_set(swigCPtr, this, value);
  }

  public int getUse_no_update() {
    return pjsuaJNI.csipsimple_config_use_no_update_get(swigCPtr, this);
  }

  public void setTurn_username(pj_str_t value) {
    pjsuaJNI.csipsimple_config_turn_username_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getTurn_username() {
    long cPtr = pjsuaJNI.csipsimple_config_turn_username_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setTurn_password(pj_str_t value) {
    pjsuaJNI.csipsimple_config_turn_password_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getTurn_password() {
    long cPtr = pjsuaJNI.csipsimple_config_turn_password_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setUse_zrtp(int value) {
    pjsuaJNI.csipsimple_config_use_zrtp_set(swigCPtr, this, value);
  }

  public int getUse_zrtp() {
    return pjsuaJNI.csipsimple_config_use_zrtp_get(swigCPtr, this);
  }

  public csipsimple_config() {
    this(pjsuaJNI.new_csipsimple_config(), true);
  }

}
