/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public enum pj_qos_type {
  PJ_QOS_TYPE_BEST_EFFORT,
  PJ_QOS_TYPE_BACKGROUND,
  PJ_QOS_TYPE_VIDEO,
  PJ_QOS_TYPE_VOICE,
  PJ_QOS_TYPE_CONTROL;

  public final int swigValue() {
    return swigValue;
  }

  public static pj_qos_type swigToEnum(int swigValue) {
    pj_qos_type[] swigValues = pj_qos_type.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (pj_qos_type swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + pj_qos_type.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private pj_qos_type() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private pj_qos_type(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private pj_qos_type(pj_qos_type swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

