/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pj_str_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public pj_str_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(pj_str_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsuaJNI.delete_pj_str_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected static long[] cArrayUnwrap(pj_str_t[] arrayWrapper) {
      long[] cArray = new long[arrayWrapper.length];
      for (int i=0; i<arrayWrapper.length; i++)
        cArray[i] = pj_str_t.getCPtr(arrayWrapper[i]);
      return cArray;
  }

  protected static pj_str_t[] cArrayWrap(long[] cArray, boolean cMemoryOwn) {
    pj_str_t[] arrayWrapper = new pj_str_t[cArray.length];
    for (int i=0; i<cArray.length; i++)
      arrayWrapper[i] = new pj_str_t(cArray[i], cMemoryOwn);
    return arrayWrapper;
  }

  public void setPtr(String value) {
    pjsuaJNI.pj_str_t_ptr_set(swigCPtr, this, value);
  }

  public String getPtr() {
    return pjsuaJNI.pj_str_t_ptr_get(swigCPtr, this);
  }

  public void setSlen(int value) {
    pjsuaJNI.pj_str_t_slen_set(swigCPtr, this, value);
  }

  public int getSlen() {
    return pjsuaJNI.pj_str_t_slen_get(swigCPtr, this);
  }

  public pj_str_t() {
    this(pjsuaJNI.new_pj_str_t(), true);
  }

}
