/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pj_str_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pj_str_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pj_str_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsuaJNI.delete_pj_str_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPtr(String value) {
    pjsuaJNI.pj_str_t_ptr_set(swigCPtr, this, value);
  }

  public String getPtr() {
    return pjsuaJNI.pj_str_t_ptr_get(swigCPtr, this);
  }

  public void setSlen(SWIGTYPE_p_pj_ssize_t value) {
    pjsuaJNI.pj_str_t_slen_set(swigCPtr, this, SWIGTYPE_p_pj_ssize_t.getCPtr(value));
  }

  public SWIGTYPE_p_pj_ssize_t getSlen() {
    return new SWIGTYPE_p_pj_ssize_t(pjsuaJNI.pj_str_t_slen_get(swigCPtr, this), true);
  }

  public pj_str_t() {
    this(pjsuaJNI.new_pj_str_t(), true);
  }

}
