/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public enum pjmedia_zrtp_use {
  PJMEDIA_NO_ZRTP(pjsuaJNI.PJMEDIA_NO_ZRTP_get()),
  PJMEDIA_CREATE_ZRTP(pjsuaJNI.PJMEDIA_CREATE_ZRTP_get());

  public final int swigValue() {
    return swigValue;
  }

  public static pjmedia_zrtp_use swigToEnum(int swigValue) {
    pjmedia_zrtp_use[] swigValues = pjmedia_zrtp_use.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (pjmedia_zrtp_use swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + pjmedia_zrtp_use.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private pjmedia_zrtp_use() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private pjmedia_zrtp_use(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private pjmedia_zrtp_use(pjmedia_zrtp_use swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

