/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjmedia_codec_param_info {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjmedia_codec_param_info(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjmedia_codec_param_info obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsuaJNI.delete_pjmedia_codec_param_info(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setClock_rate(long value) {
    pjsuaJNI.pjmedia_codec_param_info_clock_rate_set(swigCPtr, this, value);
  }

  public long getClock_rate() {
    return pjsuaJNI.pjmedia_codec_param_info_clock_rate_get(swigCPtr, this);
  }

  public void setChannel_cnt(long value) {
    pjsuaJNI.pjmedia_codec_param_info_channel_cnt_set(swigCPtr, this, value);
  }

  public long getChannel_cnt() {
    return pjsuaJNI.pjmedia_codec_param_info_channel_cnt_get(swigCPtr, this);
  }

  public void setAvg_bps(long value) {
    pjsuaJNI.pjmedia_codec_param_info_avg_bps_set(swigCPtr, this, value);
  }

  public long getAvg_bps() {
    return pjsuaJNI.pjmedia_codec_param_info_avg_bps_get(swigCPtr, this);
  }

  public void setMax_bps(long value) {
    pjsuaJNI.pjmedia_codec_param_info_max_bps_set(swigCPtr, this, value);
  }

  public long getMax_bps() {
    return pjsuaJNI.pjmedia_codec_param_info_max_bps_get(swigCPtr, this);
  }

  public void setFrm_ptime(int value) {
    pjsuaJNI.pjmedia_codec_param_info_frm_ptime_set(swigCPtr, this, value);
  }

  public int getFrm_ptime() {
    return pjsuaJNI.pjmedia_codec_param_info_frm_ptime_get(swigCPtr, this);
  }

  public void setEnc_ptime(int value) {
    pjsuaJNI.pjmedia_codec_param_info_enc_ptime_set(swigCPtr, this, value);
  }

  public int getEnc_ptime() {
    return pjsuaJNI.pjmedia_codec_param_info_enc_ptime_get(swigCPtr, this);
  }

  public void setPcm_bits_per_sample(short value) {
    pjsuaJNI.pjmedia_codec_param_info_pcm_bits_per_sample_set(swigCPtr, this, value);
  }

  public short getPcm_bits_per_sample() {
    return pjsuaJNI.pjmedia_codec_param_info_pcm_bits_per_sample_get(swigCPtr, this);
  }

  public void setPt(short value) {
    pjsuaJNI.pjmedia_codec_param_info_pt_set(swigCPtr, this, value);
  }

  public short getPt() {
    return pjsuaJNI.pjmedia_codec_param_info_pt_get(swigCPtr, this);
  }

  public pjmedia_codec_param_info() {
    this(pjsuaJNI.new_pjmedia_codec_param_info(), true);
  }

}
