/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjmedia_codec_param {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjmedia_codec_param(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjmedia_codec_param obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsuaJNI.delete_pjmedia_codec_param(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public pjmedia_codec_param_setting getSetting() {
    long cPtr = pjsuaJNI.pjmedia_codec_param_setting_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pjmedia_codec_param_setting(cPtr, false);
  }

  public pjmedia_codec_param_info getInfo() {
    long cPtr = pjsuaJNI.pjmedia_codec_param_info_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pjmedia_codec_param_info(cPtr, false);
  }

  public pjmedia_codec_param() {
    this(pjsuaJNI.new_pjmedia_codec_param(), true);
  }

}
