/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjsip_event_body_user {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjsip_event_body_user(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjsip_event_body_user obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsuaJNI.delete_pjsip_event_body_user(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUser1(byte[] value) {
    pjsuaJNI.pjsip_event_body_user_user1_set(swigCPtr, this, value);
  }

  public byte[] getUser1() {
	return pjsuaJNI.pjsip_event_body_user_user1_get(swigCPtr, this);
}

  public void setUser2(byte[] value) {
    pjsuaJNI.pjsip_event_body_user_user2_set(swigCPtr, this, value);
  }

  public byte[] getUser2() {
	return pjsuaJNI.pjsip_event_body_user_user2_get(swigCPtr, this);
}

  public void setUser3(byte[] value) {
    pjsuaJNI.pjsip_event_body_user_user3_set(swigCPtr, this, value);
  }

  public byte[] getUser3() {
	return pjsuaJNI.pjsip_event_body_user_user3_get(swigCPtr, this);
}

  public void setUser4(byte[] value) {
    pjsuaJNI.pjsip_event_body_user_user4_set(swigCPtr, this, value);
  }

  public byte[] getUser4() {
	return pjsuaJNI.pjsip_event_body_user_user4_get(swigCPtr, this);
}

  public pjsip_event_body_user() {
    this(pjsuaJNI.new_pjsip_event_body_user(), true);
  }

}
