/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjsip_event_body {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjsip_event_body(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjsip_event_body obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsuaJNI.delete_pjsip_event_body(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public pjsip_event_body_user getUser() {
    long cPtr = pjsuaJNI.pjsip_event_body_user_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pjsip_event_body_user(cPtr, false);
  }

  public pjsip_event_body_rx_msg getRx_msg() {
    long cPtr = pjsuaJNI.pjsip_event_body_rx_msg_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pjsip_event_body_rx_msg(cPtr, false);
  }

  public pjsip_event_body_tx_error getTx_error() {
    long cPtr = pjsuaJNI.pjsip_event_body_tx_error_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pjsip_event_body_tx_error(cPtr, false);
  }

  public pjsip_event_body_tx_msg getTx_msg() {
    long cPtr = pjsuaJNI.pjsip_event_body_tx_msg_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pjsip_event_body_tx_msg(cPtr, false);
  }

  public pjsip_event_body_tsx_state getTsx_state() {
    long cPtr = pjsuaJNI.pjsip_event_body_tsx_state_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pjsip_event_body_tsx_state(cPtr, false);
  }

  public pjsip_event_body_timer getTimer() {
    long cPtr = pjsuaJNI.pjsip_event_body_timer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pjsip_event_body_timer(cPtr, false);
  }

  public pjsip_event_body() {
    this(pjsuaJNI.new_pjsip_event_body(), true);
  }

}
