/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjsip_event_body_timer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjsip_event_body_timer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjsip_event_body_timer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsuaJNI.delete_pjsip_event_body_timer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEntry(SWIGTYPE_p_pj_timer_entry value) {
    pjsuaJNI.pjsip_event_body_timer_entry_set(swigCPtr, this, SWIGTYPE_p_pj_timer_entry.getCPtr(value));
  }

  public SWIGTYPE_p_pj_timer_entry getEntry() {
    long cPtr = pjsuaJNI.pjsip_event_body_timer_entry_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_pj_timer_entry(cPtr, false);
  }

  public pjsip_event_body_timer() {
    this(pjsuaJNI.new_pjsip_event_body_timer(), true);
  }

}
