/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjsip_cred_info_ext {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjsip_cred_info_ext(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjsip_cred_info_ext obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsuaJNI.delete_pjsip_cred_info_ext(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public pjsip_cred_info_ext_aka getAka() {
    long cPtr = pjsuaJNI.pjsip_cred_info_ext_aka_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pjsip_cred_info_ext_aka(cPtr, false);
  }

  public pjsip_cred_info_ext() {
    this(pjsuaJNI.new_pjsip_cred_info_ext(), true);
  }

}
