/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjsip_event_body_tx_error {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjsip_event_body_tx_error(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjsip_event_body_tx_error obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsuaJNI.delete_pjsip_event_body_tx_error(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTdata(SWIGTYPE_p_pjsip_tx_data value) {
    pjsuaJNI.pjsip_event_body_tx_error_tdata_set(swigCPtr, this, SWIGTYPE_p_pjsip_tx_data.getCPtr(value));
  }

  public SWIGTYPE_p_pjsip_tx_data getTdata() {
    long cPtr = pjsuaJNI.pjsip_event_body_tx_error_tdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_pjsip_tx_data(cPtr, false);
  }

  public void setTsx(SWIGTYPE_p_pjsip_transaction value) {
    pjsuaJNI.pjsip_event_body_tx_error_tsx_set(swigCPtr, this, SWIGTYPE_p_pjsip_transaction.getCPtr(value));
  }

  public SWIGTYPE_p_pjsip_transaction getTsx() {
    long cPtr = pjsuaJNI.pjsip_event_body_tx_error_tsx_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_pjsip_transaction(cPtr, false);
  }

  public pjsip_event_body_tx_error() {
    this(pjsuaJNI.new_pjsip_event_body_tx_error(), true);
  }

}
