/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjsip_event_body_tsx_state {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjsip_event_body_tsx_state(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjsip_event_body_tsx_state obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsuaJNI.delete_pjsip_event_body_tsx_state(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTsx(SWIGTYPE_p_pjsip_transaction value) {
    pjsuaJNI.pjsip_event_body_tsx_state_tsx_set(swigCPtr, this, SWIGTYPE_p_pjsip_transaction.getCPtr(value));
  }

  public SWIGTYPE_p_pjsip_transaction getTsx() {
    long cPtr = pjsuaJNI.pjsip_event_body_tsx_state_tsx_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_pjsip_transaction(cPtr, false);
  }

  public void setPrev_state(int value) {
    pjsuaJNI.pjsip_event_body_tsx_state_prev_state_set(swigCPtr, this, value);
  }

  public int getPrev_state() {
    return pjsuaJNI.pjsip_event_body_tsx_state_prev_state_get(swigCPtr, this);
  }

  public void setType(pjsip_event_id_e value) {
    pjsuaJNI.pjsip_event_body_tsx_state_type_set(swigCPtr, this, value.swigValue());
  }

  public pjsip_event_id_e getType() {
    return pjsip_event_id_e.swigToEnum(pjsuaJNI.pjsip_event_body_tsx_state_type_get(swigCPtr, this));
  }

  public pjsip_event_body_tsx_state_src getSrc() {
    long cPtr = pjsuaJNI.pjsip_event_body_tsx_state_src_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pjsip_event_body_tsx_state_src(cPtr, false);
  }

  public pjsip_event_body_tsx_state() {
    this(pjsuaJNI.new_pjsip_event_body_tsx_state(), true);
  }

}
