/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjsip_tls_setting {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjsip_tls_setting(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjsip_tls_setting obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsuaJNI.delete_pjsip_tls_setting(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCa_list_file(pj_str_t value) {
    pjsuaJNI.pjsip_tls_setting_ca_list_file_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getCa_list_file() {
    long cPtr = pjsuaJNI.pjsip_tls_setting_ca_list_file_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setCert_file(pj_str_t value) {
    pjsuaJNI.pjsip_tls_setting_cert_file_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getCert_file() {
    long cPtr = pjsuaJNI.pjsip_tls_setting_cert_file_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setPrivkey_file(pj_str_t value) {
    pjsuaJNI.pjsip_tls_setting_privkey_file_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getPrivkey_file() {
    long cPtr = pjsuaJNI.pjsip_tls_setting_privkey_file_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setPassword(pj_str_t value) {
    pjsuaJNI.pjsip_tls_setting_password_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getPassword() {
    long cPtr = pjsuaJNI.pjsip_tls_setting_password_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setMethod(int value) {
    pjsuaJNI.pjsip_tls_setting_method_set(swigCPtr, this, value);
  }

  public int getMethod() {
    return pjsuaJNI.pjsip_tls_setting_method_get(swigCPtr, this);
  }

  public void setCiphers(pj_str_t value) {
    pjsuaJNI.pjsip_tls_setting_ciphers_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getCiphers() {
    long cPtr = pjsuaJNI.pjsip_tls_setting_ciphers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setServer_name(pj_str_t value) {
    pjsuaJNI.pjsip_tls_setting_server_name_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getServer_name() {
    long cPtr = pjsuaJNI.pjsip_tls_setting_server_name_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setVerify_server(int value) {
    pjsuaJNI.pjsip_tls_setting_verify_server_set(swigCPtr, this, value);
  }

  public int getVerify_server() {
    return pjsuaJNI.pjsip_tls_setting_verify_server_get(swigCPtr, this);
  }

  public void setVerify_client(int value) {
    pjsuaJNI.pjsip_tls_setting_verify_client_set(swigCPtr, this, value);
  }

  public int getVerify_client() {
    return pjsuaJNI.pjsip_tls_setting_verify_client_get(swigCPtr, this);
  }

  public void setRequire_client_cert(int value) {
    pjsuaJNI.pjsip_tls_setting_require_client_cert_set(swigCPtr, this, value);
  }

  public int getRequire_client_cert() {
    return pjsuaJNI.pjsip_tls_setting_require_client_cert_get(swigCPtr, this);
  }

  public void setTimeout(SWIGTYPE_p_pj_time_val value) {
    pjsuaJNI.pjsip_tls_setting_timeout_set(swigCPtr, this, SWIGTYPE_p_pj_time_val.getCPtr(value));
  }

  public SWIGTYPE_p_pj_time_val getTimeout() {
    return new SWIGTYPE_p_pj_time_val(pjsuaJNI.pjsip_tls_setting_timeout_get(swigCPtr, this), true);
  }

  public void setQos_type(SWIGTYPE_p_pj_qos_type value) {
    pjsuaJNI.pjsip_tls_setting_qos_type_set(swigCPtr, this, SWIGTYPE_p_pj_qos_type.getCPtr(value));
  }

  public SWIGTYPE_p_pj_qos_type getQos_type() {
    return new SWIGTYPE_p_pj_qos_type(pjsuaJNI.pjsip_tls_setting_qos_type_get(swigCPtr, this), true);
  }

  public void setQos_params(SWIGTYPE_p_pj_qos_params value) {
    pjsuaJNI.pjsip_tls_setting_qos_params_set(swigCPtr, this, SWIGTYPE_p_pj_qos_params.getCPtr(value));
  }

  public SWIGTYPE_p_pj_qos_params getQos_params() {
    return new SWIGTYPE_p_pj_qos_params(pjsuaJNI.pjsip_tls_setting_qos_params_get(swigCPtr, this), true);
  }

  public void setQos_ignore_error(int value) {
    pjsuaJNI.pjsip_tls_setting_qos_ignore_error_set(swigCPtr, this, value);
  }

  public int getQos_ignore_error() {
    return pjsuaJNI.pjsip_tls_setting_qos_ignore_error_get(swigCPtr, this);
  }

  public pjsip_tls_setting() {
    this(pjsuaJNI.new_pjsip_tls_setting(), true);
  }

}
