/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjsua_call_info_buf_ {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjsua_call_info_buf_(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjsua_call_info_buf_ obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsuaJNI.delete_pjsua_call_info_buf_(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLocal_info(String value) {
    pjsuaJNI.pjsua_call_info_buf__local_info_set(swigCPtr, this, value);
  }

  public String getLocal_info() {
    return pjsuaJNI.pjsua_call_info_buf__local_info_get(swigCPtr, this);
  }

  public void setLocal_contact(String value) {
    pjsuaJNI.pjsua_call_info_buf__local_contact_set(swigCPtr, this, value);
  }

  public String getLocal_contact() {
    return pjsuaJNI.pjsua_call_info_buf__local_contact_get(swigCPtr, this);
  }

  public void setRemote_info(String value) {
    pjsuaJNI.pjsua_call_info_buf__remote_info_set(swigCPtr, this, value);
  }

  public String getRemote_info() {
    return pjsuaJNI.pjsua_call_info_buf__remote_info_get(swigCPtr, this);
  }

  public void setRemote_contact(String value) {
    pjsuaJNI.pjsua_call_info_buf__remote_contact_set(swigCPtr, this, value);
  }

  public String getRemote_contact() {
    return pjsuaJNI.pjsua_call_info_buf__remote_contact_get(swigCPtr, this);
  }

  public void setCall_id(String value) {
    pjsuaJNI.pjsua_call_info_buf__call_id_set(swigCPtr, this, value);
  }

  public String getCall_id() {
    return pjsuaJNI.pjsua_call_info_buf__call_id_get(swigCPtr, this);
  }

  public void setLast_status_text(String value) {
    pjsuaJNI.pjsua_call_info_buf__last_status_text_set(swigCPtr, this, value);
  }

  public String getLast_status_text() {
    return pjsuaJNI.pjsua_call_info_buf__last_status_text_get(swigCPtr, this);
  }

  public pjsua_call_info_buf_() {
    this(pjsuaJNI.new_pjsua_call_info_buf_(), true);
  }

}
