/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public enum pjsua_call_flag {
  PJSUA_CALL_UNHOLD(pjsuaJNI.PJSUA_CALL_UNHOLD_get()),
  PJSUA_CALL_UPDATE_CONTACT(pjsuaJNI.PJSUA_CALL_UPDATE_CONTACT_get());

  public final int swigValue() {
    return swigValue;
  }

  public static pjsua_call_flag swigToEnum(int swigValue) {
    pjsua_call_flag[] swigValues = pjsua_call_flag.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (pjsua_call_flag swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + pjsua_call_flag.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private pjsua_call_flag() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private pjsua_call_flag(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private pjsua_call_flag(pjsua_call_flag swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

