/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class SWIGTYPE_p_pj_time_val {
  private long swigCPtr;

  protected SWIGTYPE_p_pj_time_val(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_pj_time_val() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_pj_time_val obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

