/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class SWIGTYPE_p_p_pjmedia_port {
  private long swigCPtr;

  protected SWIGTYPE_p_p_pjmedia_port(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_p_pjmedia_port() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_p_pjmedia_port obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

