/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class SWIGTYPE_jobject {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SWIGTYPE_jobject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SWIGTYPE_jobject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

