/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class SWIGTYPE_p_pjsip_endpoint {
  private long swigCPtr;

  protected SWIGTYPE_p_pjsip_endpoint(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_pjsip_endpoint() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_pjsip_endpoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

